/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: OWL (https://sketchfab.com/owl06)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/psyduck-75ee040c5394475481652b9064889728
Title: Psyduck (싸이덕)
*/

import { useGLTF } from '@react-three/drei'

export function Psyduck(props) {
  const { nodes, materials } = useGLTF('/psyduck.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh castShadow receiveShadow geometry={nodes.Sphere_whilte_0.geometry} material={materials.whilte} />
          <mesh castShadow receiveShadow geometry={nodes.Sphere_black_0.geometry} material={materials.black} />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_main_color_0.geometry}
          material={materials.main_color}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_main_color_0.geometry}
          material={materials.main_color}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_second_color_0.geometry}
          material={materials.second_color}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_second_color_0.geometry}
          material={materials.second_color}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_main_color_0.geometry}
          material={materials.main_color}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane_hair_0.geometry}
          material={materials.hair}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/psyduck.glb')
