/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jimmyho905 (https://sketchfab.com/jimmyho905)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/squirtle-007-sv-bae1f85114814ebc9c09af1eaff9b85e
Title: Squirtle 007 SV
*/

import { useGLTF } from '@react-three/drei'
import { useMemo } from 'react'

function Squirtle({ props }) {
  const { nodes, materials } = useGLTF('/squirtle.glb')

  // Ottimizzazione: memoizza i materiali per evitare re-creazione
  const optimizedMaterials = useMemo(() => {
    // Abilita frustum culling per migliori performance
    Object.values(materials).forEach((material) => {
      material.side = 0 // FrontSide only (default, ma esplicito)
    })
    return materials
  }, [materials])

  return (
    <group {...props} dispose={null} position-y={-2}>
      <group scale={0.01}>
        <group scale={1000}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_55.geometry}
            material={optimizedMaterials.body_a}
            skeleton={nodes.Object_55.skeleton}
            frustumCulled
          />
          <skinnedMesh
            geometry={nodes.Object_56.geometry}
            material={optimizedMaterials.body_b_01}
            skeleton={nodes.Object_56.skeleton}
            frustumCulled
          />
          <skinnedMesh
            geometry={nodes.Object_57.geometry}
            material={optimizedMaterials['eye.R']}
            skeleton={nodes.Object_57.skeleton}
            frustumCulled
          />
          <skinnedMesh
            geometry={nodes.Object_58.geometry}
            material={optimizedMaterials['eye.L']}
            skeleton={nodes.Object_58.skeleton}
            frustumCulled
          />
          <skinnedMesh
            geometry={nodes.Object_59.geometry}
            material={optimizedMaterials.body_b_00}
            skeleton={nodes.Object_59.skeleton}
            frustumCulled
          />
          <skinnedMesh
            geometry={nodes.Object_61.geometry}
            material={optimizedMaterials.Scarf}
            skeleton={nodes.Object_61.skeleton}
            frustumCulled
          />
        </group>
      </group>
    </group>
  )
}

// Preload con Draco compression se disponibile
useGLTF.preload('/squirtle.glb')

export default Squirtle
